### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [nxtrace/NextTraceroute#2]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical. Was that APK really built from a clean tree at the commit the tag points to? If so, did I miss some build options? And if not, which commit was it?

Here's the APK diff:

```diff
-------------------------------
--- /dev/fd/63  2024-07-10 12:17:04.768949439 +0200
+++ /dev/fd/62  2024-07-10 12:17:04.768949439 +0200
@@ -3,13 +3,13 @@
   META-INF/version-control-info.textproto
   32-bit CRC value (hex):                         5faeab1c
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         9df1541e
+  32-bit CRC value (hex):                         950f7a29
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         429d1f7d
   classes.dex
   32-bit CRC value (hex):                         450ba719
   classes2.dex
-  32-bit CRC value (hex):                         3ff88b45
+  32-bit CRC value (hex):                         597d8c4b
   DebugProbesKt.bin
   32-bit CRC value (hex):                         d5ac4dc2
   META-INF/androidx.activity_activity-compose.version
@@ -125,7 +125,7 @@
   okhttp3/internal/publicsuffix/publicsuffixes.gz
   32-bit CRC value (hex):                         f59fa4f6
   AndroidManifest.xml
-  32-bit CRC value (hex):                         14de68bc
+  32-bit CRC value (hex):                         2cf529f2
   res/-6.webp
   32-bit CRC value (hex):                         0b16d868
```

Seeing `AndroidManifest.xml` being affected, too, I took a diff from that as well – which turned out to be interesting:

```diff
-    A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=7
-    A: http://schemas.android.com/apk/res/android:versionName(0x0101021c)="0.0.7" (Raw: "0.0.7")
+    A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=6
+    A: http://schemas.android.com/apk/res/android:versionName(0x0101021c)="0.0.6" (Raw: "0.0.6")
```

So definitely not built from a clean tree at the tagged commit. Maybe local, uncommitted changes? The later commits seem to only affect the Readme.

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

cc @obfusk

**Comment by surfaceocean** [comment]
@IzzySoft Thanks for your report. I've used Github actions to build automatically. You can try v0.0.8.

**Comment by IzzySoft** [comment]
On it, thanks! Will report as soon as the build is through here.

**Comment by IzzySoft** [comment]
Hm… well…

Congrats :partying_face: :star_struck: 

```
--- END BUILD LOG ---
Keeping '28a63e588f23ca126a20c8a409d4ead9a33cdb3eac6107e08976361bb4dc4b0b-com.surfaceocean.nexttraceroute-v0.0.8-upstream.apk'...
Keeping '973455ea2dc2a84ad905fdac1bb410be680e79a78cf2a74ff4e0eddda2280ca3-com.surfaceocean.nexttraceroute-v0.0.8-unsigned.apk'...
Reproducible: True
```

<s>Once v0.0.8 was pulled and sync'd (around 6 pm UTC with the regular sync), it will have the green shield.</s> Was already pulled today, wow – OK, so the shield is already up now!

![image](https://github.com/user-attachments/assets/84529e4c-e451-46ac-8c1a-2a55e5d695d6)

And welcome toot is out (meanwhile with an annotation v0.0.8 is already there):

![image](https://github.com/user-attachments/assets/1b1bb833-7739-4cd4-8730-d148387b1d6c)

([source](https://floss.social/@IzzyOnDroid/112990295865690780))

So maybe you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link to [your app at IzzyOnDroid](https://apt.izzysoft.de/packages/com.surfaceocean.nexttraceroute), so the PlayStore badge does not feel so lonely on your Readme? :wink: 

Oh, btw, before I close the issue here:

![image](https://github.com/user-attachments/assets/7f13b6c9-8b34-4bcc-805c-501dec06cea4)

that can easily be avoided with a minor addition to your `build.gradle.kts`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

**Comment by surfaceocean** [comment]
Nice. The new ’dependenciesInfo‘ has been committed and will take effect in the next release.

**Comment by IzzySoft** [comment]
Thanks! Should PlayStore complain one day, you can skip the `includeInBundle` line as we only take the APK here.
