### ISSUE TITLE
Google Play 上的最新版 IP 的信息不会显示

### ISSUE THREAD

**Issue by wx2020** [nxtrace/NextTraceroute#3]
这是首页：
![35efcc58d7762821b005e8481388011](https://github.com/user-attachments/assets/d74415ff-3253-44f4-89a4-79b8fe157667)
这是设置页：
![6a78ea5f492a50231b14d4883dc9471](https://github.com/user-attachments/assets/14a33336-1dc2-4c57-8d87-fbdcec1da9e0)

请问是 API 访问有问题吗？但我 Ping API 地址也能 Ping 通

**Comment by surfaceocean** [comment]
您好，刚刚测试了没有问题，您可以修改DNS地址，或者把DNS模式改成doh，并把doh服务器选择为223.5.5.5再试一下
